### ISSUE TITLE
Error: Cannot find module 'blanket'

### ISSUE THREAD

**Issue by Quagh** [jamesramsay/hercule#16]
Just did a clean global install of Hercule. First attempt to run it:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'blanket'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/hercule/lib/main.js:5:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/hercule/lib/main.js:80:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Mac OS X Yosemite

It did give me these errors upon installation though:

```
$ sudo npm install -g hercule
/usr/local/bin/hercule -> /usr/local/lib/node_modules/hercule/bin/transclude
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/tar-fs/node_modules/tar-stream/node_modules/bl requires readable-stream@'~1.0.26' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.33-1
hercule@0.2.0 /usr/local/lib/node_modules/hercule
├── async@0.9.0
├── pegjs@0.8.0
├── lodash@3.5.0
└── dashdash@1.7.3 (assert-plus@0.1.5)
```

**Comment by Quagh** [comment]
Uninstalled npm and node, tried again:

```
/usr/local/bin/hercule -> /usr/local/lib/node_modules/hercule/bin/transclude
hercule@0.2.0 /usr/local/lib/node_modules/hercule
├── async@0.9.0
├── pegjs@0.8.0
├── dashdash@1.7.3 (assert-plus@0.1.5)
└── lodash@3.5.0
```

So no errors when installing, but still the same `blanket` error.

**Comment by bensleveritt** [comment]
Blanket isn't installed as a normal dependancy, which is understandable since it is for development, and the unused `require(blanket)` in `main.js` is possibly unnecessary for normal use.

Removing the references, or installing [Blanket](https://www.npmjs.com/package/blanket) gets Hercule up and running again, but without knowing more about how Blanket does it's job, I'd rather leave it to the maintainer to fix.

**Comment by Quagh** [comment]
I've tweaked it for myself, but obviously I can't ask every developer in our team to do the same. I forked it, but I can't push it to npm so still waiting for the maintainer to fix it.

@jamesramsay

**Comment by jamesramsay** [comment]
Thanks for the bug report. I've been traveling without internet for the past 2 weeks.

I've made a quick patch which should fix.

**Comment by jamesramsay** [comment]
Alas, I don't have anyway to deploy it to NPM from my iPhone. I'll be back online in 5 days. Thanks for your patience.

**Comment by jamesramsay** [comment]
@Quagh @bensleveritt I've pushed a fix to NPM :+1:
