### ISSUE TITLE
Library example throws error

### ISSUE THREAD

**Issue by Dashron** [jamesramsay/hercule#178]
In the Readme (https://github.com/jamesramsay/hercule#usage), there is an example describing how to use this library. This example does not currently work as described in node 4.2.1.

It specifically errors at the very start of `transcludeStringSync` in lib/hercule.js

```js
function transcludeStringSync(input, _ref2, log) {
  var relativePath = _ref2.relativePath;
```
The example in the Readme does not provide a second parameter, so in the above function _ref2 does not exist, and accessing relativePath on _ref2 throws an error.

This is fixed by providing an object as the second parameter, with a relativePath property.

```js
var hercule = require('hercule');

var output = hercule.transcludeStringSync("# Title\n\n:[abstract](abstract.md)", {
    relativePath: __dirname
});

console.log(output);
```
Which side of this problem do you think needs to be fixed? Is relativePath a required option? Or should the function declare that field optional?

**Comment by jamesramsay** [comment]
@Dashron it should be optional. I've been planning to add more detailed tests for these interfaces.

**Comment by Dashron** [comment]
Sounds good, thanks for the quick response!

**Comment by jamesramsay** [comment]
@Dashron no worries. I should have had better unit test coverage of this. Thanks for pointing it out.
