### ISSUE TITLE
Source maps for linting

### ISSUE THREAD

**Issue by jamesramsay** [jamesramsay/hercule#208]
When working on a large API Blueprint document spread over multiple files, it would be useful for linting (e.g. https://github.com/zdne/linter-api-blueprint) to provide the feedback based on the compiled output rather on each unit.

In order for this to be possible:
- source map output from Hercule
- linter would need to detect source map, identify which files are referenced from it so that they are linted based on compiled output rather than source

**Comment by call-a3** [comment]
I concur that source maps would be a very nice addition

**Comment by jamesramsay** [comment]
Sourcemap support added in hercule@3.1. For usage in the wild see [apilint](https://github.com/danielgtaylor/apilint).
