### ISSUE TITLE
Fuzzy local link resolving

### ISSUE THREAD

**Issue by jmatsushita** [jamesramsay/hercule#218]
Hi there,

I'm trying to allow authors to transclude with a simpler link syntax in the same way that using permalinks in a static site generator allows to create links and forego the extensions (in an SSG by renaming `something.html` to `something/index.html` which means that `[my permalink](something)` works which is a more "human" link. I'd like to be able to do `:[my permatransclusion](something)` and have hercules try `something` and if asked to (with some kind of config flag I guess) then try to resolve `something.md`.

Would this be possible?

Cheers,

Jun

**Comment by jmatsushita** [comment]
Forgot to say: It should also then finally try `something/index.md`

**Comment by jamesramsay** [comment]
Interesting idea. I wonder if this could be achieved by exposing an API to allow custom local link resolution? This could also be the solution for using hercule in the browser?

**Comment by jmatsushita** [comment]
Being able to pass a callback for custom local link resolution sounds like it would do the trick indeed!

**Comment by jamesramsay** [comment]
@jmatsushita I've just released a new version (`4.0.0-beta.1`) to npm which exposes a new `resolver` API which allows you to provide your owns functions for resolving links. See https://github.com/jamesramsay/hercule#resolvers

I think this should solve your situation. Let me know if you need a hand or run into any troubles!

**Comment by jamesramsay** [comment]
Closing. Please let me know if you have any feedback. Happy to re-open this issue to discuss further.
