### ISSUE TITLE
Support for HTTP links

### ISSUE THREAD

**Issue by jamesramsay** [jamesramsay/hercule#22]
Links currently must be relative file links. It could be interesting to reference remote files, but not sure what instances this would be particularly useful in...

**Comment by zdne** [comment]
...maybe when you have a common data (MSON) patterns or shared texts such as lionesses etc.. still a distant future but I can see this as a very useful thing (eventually)

**Comment by MichaelHirn** [comment]
We ran into one particular use-case. As we have multiple micro services, which share common JSON response specs (JSON schema), it would be very convenient, if we could transclude those schemas from our remote path - which also seems not yet possible with the api blueprint.

Example

```

+ Response 200

  + Schema
          :[ListJsonSchema][http://domain.com/schemas/list.json]

  + Body

```

**Comment by jamesramsay** [comment]
Thanks. Really helpful feedback and thanks for opening a PR. :+1: 

I hope to get this into a release in the next couple of days.

**Comment by jamesramsay** [comment]
Support added in release 1.1.0
