### ISSUE TITLE
Improve context passing example

### ISSUE THREAD

**Issue by jmatsushita** [jamesramsay/hercule#234]
It's a bit confusing that the example uses a required for both key and value.

```
const inputRequired = ':[Required Ingredient](cucmber.mson required:"required")'
```

```
- description: Essential for tzatziki (string, :[is required](required || "optional"))
```

Also a description of what `:[is _]` does exactly would be great (matches non null? non empty string? something else?).

Cheers!

Jun

**Comment by jamesramsay** [comment]
That's definitely confusing. It's very much a corner case I have in certain API documentation I write in MSON that I'm using to illustrate what is meant to be quite simple.

The content inside the square brackets `:[is required]` is completely ignored by hercule, except that it can't contain a line break. Thus the following are valid: `:[](link.md)` and `:[ ](link.md)`.

**Comment by jmatsushita** [comment]
I think I understand the aim and I think it's great to experiment with passing context to markdown!

I was wondering if your could do for instance:
```:[Required Ingredient](cucumber.mson required:true)```

And then in the linked MSON
```:[is required]("required" | "optional")```

Which (to me) makes it clearer that ```required``` is the variable name.

Which led to my question about how the parsing of the `is required` works. Which I'm still not sure I'm getting. My assumption was that when transcluding, the parser would replace the value of the variable ```required``` with ```true``` in my example and ```"required"``` in yours, then compute ```is required``` and use the value before the ``||```if it matches/returns true/returns non-empty (?), and after the ```||```if it doesnt.
