### ISSUE TITLE
Improve error message when linking to directory

### ISSUE THREAD

**Issue by jmatsushita** [jamesramsay/hercule#258]
Until we can resolve links in a custom way, it would be great to have more readable error messages when transclusion links point to a directory.

Currently the message returned is:
```
>> Error: EISDIR: illegal operation on a directory, read
```

And from the CLI
```
ERROR: Could not read file (undefined)
```

Which is hard to troubleshoot :)

Cheers,

Jun

**Comment by jamesramsay** [comment]
Closed #261
