### ISSUE TITLE
Optionally transcluding certain files

### ISSUE THREAD

**Issue by Ramblurr** [jamesramsay/hercule#270]
We're using Hercule + some custom gulp scripts for building and linting our API Blueprint, and our API has public and internal portions, often interleaved.

I'm looking for a solution for "optional" transcludes so we can keep our entire API spec in one project, and then build out "internal" and "public" versions.

For example if a transclude link has the extension `.private`, and based on some context the "public only", then the transclude link is not resolved and the line removed from the output.

Our gulp task for hercule looks like this:

``` js
gulp.task('hercule', false, function () {
  function gulpHercule(options) {
    return through.obj(function (file, encoding, callback) {
      if (file.isNull()) {
        return callback(null, file);
      }

      if (file.isBuffer()) {
        transcludeString(file.contents.toString(encoding), options, function (output, o2) {
          file.contents = new Buffer(o2);
          return callback(null, file);
        });
      }
    });
  }
 // if config.includeInternal == true -> include private transcludes, else exclude them
  gulp.src(config.rootAPIB, { cwd: 'src' })
      .pipe(gulpHercule({ relativePath: config.src }))
      .pipe(template(templateStrings))
      .pipe(gulp.dest(config.out));
});
```

In normal Gulp tasks, all the files are part of the pipeline, but in hercule, only the "rootAPIB" is included, which means I can't exclude files at this level.

I feel like there might be some way to use hercule references here, but I'm not sure how. Any ideas here?

**Comment by Ramblurr** [comment]
I tried to use refereces to achieve this.

```

  if(!config.includeInternal) {
    gulp.src('src/**/*')
      .pipe(tap((file) => {
        if(file.path.indexOf('.private.') > -1 ) {
          const name = file.path.substr(file.path.lastIndexOf('/')+1);
          herculeOptions.references.push({
            placeholder: name, href: '', hrefType: 'string'
          });
        }
      }));
  }
```
This snippet parses the src tree for files that contain `.private.` in their file name (example full file name: `admin.private.apib`), then parses out just the filename from the file path, and creates a blank reference object for it.

The idea is given the transclude `:[](admin.private.apib)`, this will supply the reference `{placeholder: 'admin.private.apib', href: '', hrefType: 'string}`, resulting in the transcluder outputign an empty string.

However, it seems files that exist (such as `admin.private.apib`) take precedence over the references provided, so this strategy doesn't work.

**Comment by Ramblurr** [comment]
This might be addressed by #218

**Comment by jamesramsay** [comment]
@Ramblurr did you manage to find a way to make this work?

We have a similar situation at Adslot, but we just have two different root files, one for internal and the other for external. Some sections are straight duplicates, while other sections are heavily redacted. It's not the most elegant solution, but it seems to work for us.

**Comment by Ramblurr** [comment]
Yea, we did this with a custom link resolver.

We ended up doing other custom things in the link resolver aside from the internal/external stuff, but here is  the relevant bit for that:

```js
function customLinkResolver(args, cb) {
  // exclude files if matching environment and pattern
  if ( EXCLUDE_ENVIRONMENTS.indexOf(environment)>=0 ) {
    if (args.link.match(EXCLUDE_PATTERN)) {
      gutil.log(colors.red("Skipping ", args.link));
      return cb(null,createEmptyStream());
    }
  }
return resolveLink(...arguments);
```

Those vars look like:

```
const EXCLUDE_ENVIRONMENTS = config.excludeEnvs || ['production'];
const EXCLUDE_PATTERN = config.excludePattern || /\.private\.apib$/;
```
The environment is a runtime param that we pass with `gulp build --environment=foobar`.

So, production environments have files ending in `.private.apib` excluded from the build.

This lets us use private files anywhere inside the tree of apib files.
