### ISSUE TITLE
White space in description causes errors?

### ISSUE THREAD

**Issue by whbath** [jamesramsay/hercule#31]
According to the examples the below should be a valid link:

    :[Example here](example.md)

However when I run it...
Running "hercule:docs" (hercule) task
Fatal error: Expected "]" or [a-zA-Z0-9] but " " found.

When I get rid of the white space the below works:

    :[ExampleHere](example.md)

![image](https://cloud.githubusercontent.com/assets/198242/8515697/714b4a1c-23eb-11e5-9900-98e54196dacf.png)

**Comment by jamesramsay** [comment]
Could you confirm which version you are using? This should be fixed in the most recent release.

**Comment by jamesramsay** [comment]
This is definitely working in the latest release.
