### ISSUE TITLE
Recursive transclusion

### ISSUE THREAD

**Issue by whbath** [jamesramsay/hercule#33]
Not sure if it's intended to be supported or not (if not consider this a feature request), but would be good to transclude included files; i.e.

     file1.md:
     I want to transclude [ThisOne](file2.md)

    file2.md:
    And I'm so DRY and lazy I'd like to transclude [ThisOneHere](file3.md)

    file3.md:
    Must I do everything?

**Comment by jamesramsay** [comment]
This works! However, it looks like you forgot to include the leading colon `:`.

Input:
```
file1.md:
I want to transclude :[ThisOne](file2.md)

file2.md:
And I'm so DRY and lazy I'd like to transclude :[ThisOneHere](file3.md)

file3.md:
Must I do everything?
```

Output:
```
I want to transclude And I'm so DRY and lazy I'd like to transclude Must I do everything?
```
