### ISSUE TITLE
Source maps contain duplicate generated line entries

### ISSUE THREAD

**Issue by danielgtaylor** [jamesramsay/hercule#330]
I'm trying to use source maps generated by `hercule.transcludeString('...')` to display information about the source file and line in my [API Linter](https://github.com/danielgtaylor/apilint) but am running into a strange problem. I'm not sure if this is a bug or feature, but there seem to be duplicate entries for an individual generated line in the source map. For example:

```js
{ source: '../transclude-test.apib',
  generatedLine: 1,
  generatedColumn: 0,
  originalLine: 1,
  originalColumn: 0,
  name: null }
{ source: '../transclude-test.apib',
  generatedLine: 2,
  generatedColumn: 0,
  originalLine: 2,
  originalColumn: 0,
  name: null }
{ source: '../transclude-test.apib',
  generatedLine: 3,
  generatedColumn: 0,
  originalLine: 3,
  originalColumn: 0,
  name: null }
{ source: '../transclude-test.apib',
  generatedLine: 4,
  generatedColumn: 0,
  originalLine: 4,
  originalColumn: 0,
  name: null }
{ source: '../transclude-test.apib',
  generatedLine: 5,
  generatedColumn: 0,
  originalLine: 5,
  originalColumn: 0,
  name: null }
{ source: 'included.apib',
  generatedLine: 5,
  generatedColumn: 0,
  originalLine: 1,
  originalColumn: 0,
  name: null }
{ source: 'included.apib',
  generatedLine: 6,
  generatedColumn: 0,
  originalLine: 2,
  originalColumn: 0,
  name: null }
{ source: 'included.apib',
  generatedLine: 7,
  generatedColumn: 0,
  originalLine: 3,
  originalColumn: 0,
  name: null }
{ source: 'included.apib',
  generatedLine: 8,
  generatedColumn: 0,
  originalLine: 4,
  originalColumn: 0,
  name: null }
{ source: 'included.apib',
  generatedLine: 9,
  generatedColumn: 0,
  originalLine: 5,
  originalColumn: 0,
  name: null }
{ source: 'included.apib',
  generatedLine: 10,
  generatedColumn: 0,
  originalLine: 6,
  originalColumn: 0,
  name: null }
{ source: 'included.apib',
  generatedLine: 11,
  generatedColumn: 0,
  originalLine: 7,
  originalColumn: 0,
  name: null }
{ source: 'included2.apib',
  generatedLine: 11,
  generatedColumn: 0,
  originalLine: 1,
  originalColumn: 0,
  name: null }
{ source: '../transclude-test.apib',
  generatedLine: 11,
  generatedColumn: 9,
  originalLine: 5,
  originalColumn: 41,
  name: null }
{ source: '../transclude-test.apib',
  generatedLine: 12,
  generatedColumn: 0,
  originalLine: 6,
  originalColumn: 0,
  name: null }
```

Take a look at `generatedLine: 11`. The correct source is `included2.apib` but unfortunately I have no easy way to tell that because there are three entires for that generated line.

Is this by design and if so, how do you expect downstream apps to consume it?

**Comment by jamesramsay** [comment]
Thanks for pointing this out, it clearly makes no sense for the consumer to have to determine which source is the real source. I'll look into this over the weekend.

Any chance you can share your test input so we are working off the same example?

**Comment by danielgtaylor** [comment]
@jamesramsay thanks, I appreciate it! Here are my source files that I was using to test. You can save them and use it as input to `apilint` to see the wrong file listed. Ideally I'd like to just use [`sourceMapConsumer.originalPositionFor(...)`](https://github.com/mozilla/source-map#sourcemapconsumerprototypeoriginalpositionforgeneratedposition) and have things work.

**transclude-test.apib**
```apib
# My Api

# Resources [/resources]

:[Actions for resources](./included.apib)
```

**included.apib**
```apib
## GET

+ Response 200 (application/json)

        {}

:[another one](included2.apib)
```

**included2.apib**
```apib
## DELETE
```

**Comment by jamesramsay** [comment]
I think I've found the primary cause of the issue but there seems to be one edge case left.

One of Hercule's internal behaviours is to remove the trailing newline from the end of each transcluded file. This is so that a transclusion can occur inline (e.g. `quick :[colour](brown.md) fox`) without breaking in the middle of a line which would cause problems for some whitespace sensitive scenarios (like a bulleted list).

When I test your example with `apilint` and my new branch it correctly attributes everything but the line from `included2.apib`, I think because the newline character technically sits at the end of `## DELETE` and I attribute that to `transclude-test.apib`.

Perhaps I need to re-evaluate which new line belongs to which file.

**Comment by jamesramsay** [comment]
@danielgtaylor please take a look at `hercule@3.2.0` which produces much cleaner sourcemaps. I'll close this for now, but let me know if you have any troubles.

**Comment by danielgtaylor-isp** [comment]
@jamesramsay this works great, thanks! :+1:

**Comment by danielgtaylor** [comment]
@jamesramsay this works great, thanks! :+1:
