### ISSUE TITLE
Transclude files by glob

### ISSUE THREAD

**Issue by shumkov** [jamesramsay/hercule#34]
It will be very useful for transcluding many (dynamically created?) files from dir.

**Comment by jamesramsay** [comment]
Thanks for the suggestion @Shumkov. Are imagining allowing globs in the transclude links (e.g. `This is an :[example glob link](*.md)`) or more as an input into the Hercule CLI (e.g. `hercule *.md -o onefile.md`)?

**Comment by Shumkov** [comment]
I'm not sure about cli, but in the link path looks well. Usually we have a
single main file with transclude links, and we know a name.

**Comment by jamesramsay** [comment]
Interesting. I guess the challenge is that the output document won't necessarily have a guaranteed order of content unless hercule imposes alphabetic sorting, which might not be right for everyone.

Would you be able to provide a more specific example of what the input file might look like, what sort of files you'd have in the directory and what you would expect the output to look like? Just trying to get my head around it...

**Comment by Shumkov** [comment]
It's useful when you have a many files (auto generated in my case).

You can use number prefix in file name for keeping it order.

**Comment by jamesramsay** [comment]
So, hypothetically there is a document `start.md`:

```markdown
This is an example.

:[all the files](src/*.md)
```

And a given a directory `src` containing files:

- `a.md`
- `b.md`
- `c.md`

The output should be equivalent to:

```markdown
This is an example.

:[file 1](src/a.md)
:[file 2](src/b.md)
:[file 3](src/c.md)
```

Where the glob is expanded into all the files in alphabet order, each on a new line?

**Comment by Shumkov** [comment]
Yes, seems to be right!

**Comment by jamesramsay** [comment]
@Shumkov I've released a new version `v4.0.0-beta.1` to npm which has a new API allowing custom resolvers to be specified (https://github.com/jamesramsay/hercule#resolvers).

Transcluding a glob would be very simple to implement using this API. Let me know if you need a hand or run in to challenges.

**Comment by Shumkov** [comment]
Great! Thank you.

**Comment by jamesramsay** [comment]
Closing for now. Do let me know if you implement this through the resolver API. I'd be interested in your feedback and would be keen to link to it, or merge it in as a new feature.
