### ISSUE TITLE
Escaping?

### ISSUE THREAD

**Issue by honzajavorek** [jamesramsay/hercule#378]
Hi, how do I escape the `:[]()` sequence in case I don't want it to be replaced?

**Comment by jamesramsay** [comment]
Currently there isn't any escape sequence to allows a transclusion link not to be transcluded.

What's the use case for this behaviour?

As far as I am aware there isn't an equivalent behaviour for most markdown renderers preventing a standard `[Link](http//google.com)` from being processed. This seems similar to me.

**Comment by honzajavorek** [comment]
The problem is quite funny. I wanted to mention in my docs that writers of that docs can use Hercule's `:[Title](link.md)` syntax to include other documents. But the same document is actually processed by Hercule, so this example happened to fail the build of the docs, because it tried to include the `link.md` file 😄

I wondered whether there's a way to exceptionally avoid the behavior by some escaping. Instead of mentioning the syntax, I linked to Hercule docs, but to be honest, the example would fit there much better - it's clear and immediately understandable, without further clicking and reading.

**Comment by honzajavorek** [comment]
And the original link syntax does not have escaping AFAIK, but at the same time, when you do `[Hello](http://example.com)`, it is not processed as a link.

**Comment by jamesramsay** [comment]
That makes sense. I think best way to do this would be to insert a zero width space between the colon and square bracket (`:‌‌[`), or the square bracket and parenthesis (`](`). Hercule with then completely ignore it.

This page has tips for inserting the ZWS character on different operating systems: http://www.somebits.com/weblog/tech/zero-width-space.html

**Comment by jamesramsay** [comment]
@honzajavorek any luck with this?

**Comment by honzajavorek** [comment]
I'm sorry, at a conference atm, so I didn't have time to try it out. Looks
like a good idea, the only con which popped in my head was that if sb would
copy-paste it, they would get the space as well, which would become a
problem almost impossible for them to discover/debug.

**Comment by jamesramsay** [comment]
You're right. That would be an absolute pain to debug if that happened

I'm definitely open to making a kind of change to support this your use case, but I'm short of any ideas that don't create surprising edge cases where the link isn't transcluded.

**Comment by honzajavorek** [comment]
I'll try to play with some ideas next week and get back here to share what
I came up with.

**Comment by honzajavorek** [comment]
My research reveals GFM generally supports backslashes for escaping. From their [cheat sheet](https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf):

<img width="465" alt="image" src="https://user-images.githubusercontent.com/283441/27656528-952e6aa2-5c49-11e7-84c3-e61a33706424.png">

Also, I found [something about backticks](https://gist.github.com/mcandre/8d76e076b2495fd8b36f439ec5033116) and [this SO answer](https://stackoverflow.com/a/16027856/325365) which is pretty much a showcase of how crazy the backslash thing can get.

In my understanding, escaping any special character from the `:[]()` sequence should be sufficient to break the sequence to be an active transclusion. So if I had e.g. `:\[Title](link.md)` in my source, it would display as `:[Title](link.md)` when rendered, and it wouldn't be transcluded. Maybe it already works - I did not try 😮

**Comment by jamesramsay** [comment]
Hercule ignores `:\[Title](link.md)` (verified) and Github renders `:\[Title](link.md)` as :\[Title](link.md).

Looks like problem solved? I should probably add some kind of tip to the readme to help others too.

**Comment by honzajavorek** [comment]
Great! I think this is solved then. Up to you if you want to add it to docs, I think this issue might be enough for people to google out.
