### ISSUE TITLE
Resolvers per link or per document?

### ISSUE THREAD

**Issue by jmatsushita** [jamesramsay/hercule#386]
Hi there,

Is it right that when a resolver is skipped (by returning `null` as per the docs) and there are no resolvers for a particular link then the document processing stops?

If that's so, would it be possible to have a "per link" resolution where skipping an unresolved link would leave it as is but continue to the next?

Hope its not me overlooking something obvious :)

Jun

**Comment by jamesramsay** [comment]
The current behaviour is to throw an error if all resolvers return `null`.

I went this direction because my thinking was that if a document was targeting Hercule by including transclusion links it would be easy to debug if it failed at the point in the document where invalid input was supplied. At the same time I can see scenarios where it makes sense to proceed.

I'll try to look at this soon.

**Comment by jmatsushita** [comment]
This makes sense. To keep backward compatibility maybe returning `true` could continue? Happy to try a PR if you're interested.

**Comment by jmatsushita** [comment]
Just realised that I can achieve the functionality I need by returning placeholder content in the resolver. I could even keep separation of concerns by adding a "catch all" resolver at the bottom of the stack that does that. Nice!

**Comment by jamesramsay** [comment]
@jmatsushita awesome! From memory the resolver only receives to args  the URL and the parent file, so it's not possible to reconstruct the link exact placeholder that was in the original document.

For example, in the original text (`foo.md`) a transfusion link: `:[example](bar.md fizz:"buzz")`

The resolver would only receive the args: `('bar.md', './foo.md')`.

This isn't enough to reconstruct the original placeholder. Ideally, I'd like to make it possible to write a resolver function that allows the original content to be passed through completely unmodified.

**Comment by jamesramsay** [comment]
I've created a branch (`resolver-placeholder`) that adds a third arg to resolvers API which includes the entire transclusion link (e.g. `:[foo](bar.md)`).

A catch all resolver would might then be (ES2015):

```js
const resolvers = [
  (url, source, placeholder) => { return { content: placeholder }; }
]
```

Seems like a nice addition to the API. Thanks for the suggestion! 🎉

**Comment by jmatsushita** [comment]
Ha, I'm catching up with you slowly :) I just realised that my catchAll was missing this and your PR addresses the problem perfectly! Thanks!

**Comment by jmatsushita** [comment]
And since I love conciseness you can save a few characters with:
```
const resolvers = [
  (url, source, placeholder) => ({ content: placeholder})
]
```
