### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by realityking** [jamesramsay/hercule#422]
I'd like to add support for Promises to Hercule.

Questions:

- Do you want it? 😄
- If you do, what pattern would you prfer
  1. No more support for callbacks, new major release
  2. Add separate methods that are promise based, e.g. `transcludeFile.promise`, or sth. like that
  3. Return Promise if no callback is specified

No 1 would have the benefit that it could clean up this somewhat awkward code but I'm not sure if that's worth breaking B/C.

https://github.com/jamesramsay/hercule/blob/51b7cac46d8970903ca3cf4f42a21f5fe03d7ae2/src/hercule.js#L41-L44

**Comment by jamesramsay** [comment]
Thanks for the proposal and for all your involvement @realityking :smile: 

I'm open to support for promises, but I don't want to break backwards compatibility by removing callbacks. Of the three options, I think number three is the nicest interface.

**Comment by jamesramsay** [comment]
Closed by https://github.com/jamesramsay/hercule/pull/603
