### ISSUE TITLE
Removed sync API (pre 4.x) doesn't work on Windows

### ISSUE THREAD

**Issue by b1f6c1c4** [jamesramsay/hercule#423]
**For hercule 3.x.x,** `#!/usr/bin/env node` doesn't work on windows platform. See [stackoverflow](https://stackoverflow.com/questions/38466044/node-js-cannot-read-property-tostring-of-null-when-running-package-on-window).
I suggest using the following snippet to keep a minimal change of code:
```javascript
// src/hercule.js
// const result = childProcess.spawnSync('../bin/hercule', syncArgs, syncOptions);
const result = childProcess.spawnSync('node', ['main.js', ...syncArgs], syncOptions);
```

**Comment by jamesramsay** [comment]
Thanks for the bug report. Am I right in understanding this only impacts the `sync` API that was removed in `hercule 4.x`?

**Comment by b1f6c1c4** [comment]
`git grep` and `git blame` show that the shebang file `bin/hercule` was introduced in the [initial release](https://github.com/jamesramsay/hercule/commit/db2bc86e378d89c4f25e075547195fff7576a297#diff-75ab3052d95ad6a5636f0a30017f0840R1) but only used by `transclude.*Sync` API, starting from [62c578a9](https://github.com/jamesramsay/hercule/commit/62c578a9813d059796e4f325d9028ec84e3de12b#diff-ca034b47814884faaf007845b7505561R51) and removed by [bcd7a926](https://github.com/jamesramsay/hercule/commit/bcd7a9260f0c70ef1ea6ad17b31aff964c4ad75a#diff-ca034b47814884faaf007845b7505561L81).

Though hercule@4.x distribution is (to my knowledge) functional on windows, I would recommend that use an alternative platform-independent approach to substitute `bin/hercule`.

**Comment by jamesramsay** [comment]
Thanks for confirming this. Since the sync API has been removed in the current version and my lack of access to a Windows computer, I'm closing this bug. If you would like to contribute a fix I'd be happy to merge and publish it to NPM.

From my research the `#!/usr/bin/env node` shebang shouldn't be the source of the problem.
