### ISSUE TITLE
Nested placeholders

### ISSUE THREAD

**Issue by Shumkov** [jamesramsay/hercule#44]
Passing a placeholder via some included files will be very userful and makes my project less complicated. 

first.md
```
:[](second.md placeholder:"John")
```

second.md
```
Hello :[name](placeholder)
:[](third.md placeholder:placeholder)
```

third.md
```
How are you, :[name](placeholder)?
```

**Comment by jamesramsay** [comment]
@Shumkov when you provide a placeholder to a file, it gets passed to all children unless it is overwritten.

Based on that example, in `second.md` you are overwriting the placeholder. If you simply had `:[](third.md)` it should work.

With this adjustment, I get the output:

```markdown
Hello John
How are you, John?
```
