### ISSUE TITLE
Missing file in 5.1.2: lib/promises.js

### ISSUE THREAD

**Issue by realityking** [jamesramsay/hercule#622]
Installing Hercule into my project and using the new promises API I get an error that `lib/promises.js` doesn't exist. I tried figuring out why it wasn't packaged by running `npm pack` in my local clone of hercule. Any chance there was an issue during publication?

**Comment by realityking** [comment]
@jamesramsay Can you pleas have a look at this one? 🙏

**Comment by jamesramsay** [comment]
@realityking I think I must have forgotten to recompile the `lib` directory. I've fixed this by updating the `version` script to prevent this happening in future. hercule@5.1.3 should work correctly. I have verified that `lib/promises.js` is in the bundle.

**Comment by realityking** [comment]
Awesome. It's all working now :)
