### ISSUE TITLE
Synchronous API

### ISSUE THREAD

**Issue by dgileadi** [jamesramsay/hercule#93]
I'd really like a synchronous API for hercule. It's pretty simple to make a synchronous call become asynchronous—just wrap it in a setImmediate or similar—but it's rather hard to go the other direction. As best as I can tell the only thing keeping it synchronous is support for transcluding from an HTTP address. Would you be willing to make (or accept a pull request for) a version of hercule that works synchronously, dropping support for HTTP transcludes?

**Comment by jamesramsay** [comment]
Interesting. I can see how it might be it might be nice to have a synchronous interface.
I've actually been making significant progress rebuilding the underlying structure of hercule to use streams, which pushes the code in the opposite direction to what you're after!

It might be possible to create a synchronous interface using this sort of approach: https://strongloop.com/strongblog/whats-new-in-node-js-v0-12-execsync-a-synchronous-api-for-child-processes/

I know that there are number of people who rely on the HTTP capabilities to transclude JSON schemas from an application server, so future releases will need to retain HTTP support. I'm happy to investigate this as part of the upcoming 2.0 release – hopefully a beta before Christmas, and also discuss a short term remedy if needed.

**Comment by jamesramsay** [comment]
Relevant Node docs: https://nodejs.org/api/all.html#all_synchronous_process_creation

**Comment by dgileadi** [comment]
Here's my thinking on how it might work: if you provide a callback to `transcludeString` or to `transcludeFile` then it would run asynchronously as it currently does. However if you omit a callback then it would run synchronously, and would throw an error for any functionality that needs to be asynchronous (like HTTP). I'll play with it a little to see how simple (or hard) it would be to support it.

I've looked at a few solutions for running asynchronous things synchronously, like the `sync` npm package. Unfortunately none of the things I've found are likely to work well for my current needs.

**Comment by jamesramsay** [comment]
@dgileadi I managed to get a rough version working on my v2 (WIP) branch this morning. I think the same approach would work on the current release too.

**Comment by dgileadi** [comment]
That's very cool. Thanks for looking into it!

**Comment by jamesramsay** [comment]
@dgileadi I've just published an alpha of 2.0.0 (`npm install hercule@2.0.0-alpha.1`) which includes `transcludeStringSync`. If you're happy to give it a try, I'd appreciate your feedback.

**Comment by dgileadi** [comment]
For a while I was unable to `npm install 2.0.0-alpha.1`; I guess whatever I was using was lagging behind. Now that I can I realize I’m stuck on node 0.10, and `execFileSync` isn’t available. However I’ve figured out how to run what I need asynchronously; it took some work and is hacky but it works.

On the topic of 2.0.0-alpha.1 I had to `npm install event-stream`. I’m not sure if it’s part of node 0.12 by default, but if not then maybe you’ll need to add it as a dependency.

In any case I think it's safe to consider this issue closed. Thanks so much for working on it!

**Comment by jamesramsay** [comment]
No worries. I noticed that the other day. Will push a fix shortly.

That is a good point about requiring node 0.12 for `execFileSync`. I should probably note that explicitly and add tests for 0.10 async interfaces.

Do you plan on upgrading to 0.12 soon?

**Comment by dgileadi** [comment]
Unfortunately I’m on a large project and I don’t think they’re planning on upgrading node, sadly.

**Comment by jamesramsay** [comment]
I know the feeling – it took us a long to time to move to 0.12.
